home_story4/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'jasmine'

urlpatterns = [
	path('', views.welcomepage, name='welcomepage'),
	path('profileku/', views.profile, name='profile'),
	path('regisku/',views.regisku, name="regisku"),
	path('form_fields/', views.form_fields, name='form_fields'),
	path('schedule_post/', views.schedule_post, name='schedule_post'),
	path('deleteJadwal/',views.deleteJadwal, name='deleteJadwal')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_1/urls.py
from django.urls import re_path
from .views import index
from django.conf import settings
from django.conf.urls.static import static
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import path, include
from django.contrib import admin
#from lab_1.views import index as index_lab1
#import home_story4.urls as home

urlpatterns = [
    path(r'^admin/', admin.site.urls),
    #path(r'^lab-1/', include('lab_1.urls')),
    #path(r'^lab-2/', include('lab_2.urls')),
    #path(r'^$', include(home)),
	path('',include('home_story4.urls'))
]

home_story4/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime, timedelta
    
class schedule(models.Model):
    place = models.CharField(max_length=20)
    event = models.TextField(max_length=20)
    category = models.CharField(max_length=200)
    date = models.DateField(default=date.today)
    time = models.TimeField(auto_now=False, auto_now_add=False)

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

home_story4/forms.py
from django import forms
import datetime 

class mySchedule_form(forms.Form):
	place_attrs = {
		'type': 'text',
		'class': 'todo-form-input',
		'placeholder': 'place'
	}

	place = forms.CharField(label='Tempat', required=True, widget = forms.TextInput(attrs = place_attrs))
	event = forms.CharField(label='Kegiatan',required=True,max_length='25',empty_value='Anonymous')
	category = forms.CharField(label='Kategori', required=True, initial='Event category')
	date = forms.DateField(label='Choose Date', required=True, initial=datetime.date.today, widget=forms.DateInput(attrs={'type' : 'date'}))
	time = forms.TimeField(widget=forms.TimeInput(attrs={'type' : 'time'}))
	

home_story4/views.py
from django.shortcuts import render
from .forms import mySchedule_form
from .models import schedule
from django.http import HttpResponseRedirect

# Create your views here.
from django.http import HttpResponse

response = {}

def welcomepage(request):
	return render(request, "home_story3.html")

def profile(request):
	return render(request, "profile_story3.html")

def regisku(request):
	return render(request, "regis_story3.html")

def form_fields(request):
	response['form'] = mySchedule_form
	html = 'displayForm.html'
	return render(request, html, response)

def schedule_post(request):
	form = mySchedule_form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['place'] = request.POST['place'] if request.POST ['place'] != "" else "anonymous"
		response['event'] = request.POST['event'] if request.POST ['event'] != "" else "anonymous"
		response['category'] = request.POST['category'] if request.POST ['category'] != "" else "anonymous"
		response['date'] = request.POST.get('date')
		response['time'] = request.POST['time']

		schedules = schedule(place=response['place'] , event=response['event'], category=response['category'], date=response['date'],
			time=response['time'])

		schedules.save()

		schedules = schedule.objects.all()
		response['schedules'] = schedules
		html = 'table.html'

		return render(request, html, response)


def deleteJadwal(request):
	schedule.objects.all().delete()
	response={}
	html = 'table.html'

	return render(request,html,response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Jasmine Nur Safiera' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999,5,31) #TODO Implement this, format (Year, Month, Date)
npm = 1706024841 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

home_story4/templates/displayForm.html
{% block content %}
{% load staticfiles %}

<section>
  <div style="background-color: white">
    <section class="resume-section p-3 p-lg-5 flex-column" id="projects">
      <h2 style="color: black">Add Schedule</h2>
	<div class="my-auto">
        <div class="col-sm-12 form-row field-desc">
        	<form id="form" method="POST" action="{% url 'jasmine:schedule_post' %}">
	        	{% csrf_token %}
	          {{ form }}

	        	<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
       		</form>
        </div>
    </div>
</section>

{% endblock %}

home_story4/templates/home_story3.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}

	<div class="bg1">


		<img src="{% static 'css/profpic.jpg'%}" class="profile">
		<h1>WELCOMEE</h1>

	</div>

{% endblock %}

home_story4/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Jasmine demi pepew</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/forstyle.css' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="{% url 'jasmine:welcomepage' %}">HOME</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item active">
		        <a class="nav-link" href="{% url 'jasmine:profile' %}">My Profile<span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'jasmine:regisku' %}">Registration</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'jasmine:form_fields' %}">Schedules</a>
		      </li>
		    </ul>
		  </div>
		</nav>
		{% block content %}
    	{% endblock %}
</body>

</html>

home_story4/templates/profile_story3.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<center>
	<h2>MY <img src="{%static 'css/aboutmepic.jpg' %}" class="about_me"> Profile</h2>
	</center>
	<div class="row">
		
	
	  <div class="col" style="background-color: #ffffff; margin: 1rem">
	  	<h1>It's Me!</h1>
	  	<p> nice to meet you, i'm <span style="color:black;font-weight:bold"> Jasmine Nur Safiera </span> </p>
		<p>an energetic and ambitious person <br> who has developed a mature and responsible approach to<br> any task that undertake or situation that i am presented with.</p>
	  </div>

	  <div class="col" style="background-color: #ffffff; margin: 1rem">
	  	<h1>Ktp-ku</h1>
	  	<p> Tanggal lahir : 31 mei 1999<br>Tempat Lahir : Jakarta<br>Universitas : Universitas Indonesia<br>Kewarganegaraan : Indonesia<br>status : tidak menikah<br> Bahasa : Indonesia </p>
	  </div>

	  <div class="w-100"></div>
	  <div class="col" style="background-color: #ffffff; margin: 1rem; height: 100%">
	  	<h1>Interest and Skill</h1>
	  	<p>Public Speaking</p>
			<div class="container">
			  <div class="skills pubspeak">80%</div>
			</div>

			<p>Photo Editing</p>
			<div class="container">
			  <div class="skills photed">65%</div>
			</div>

			<p>Jurnalistic</p>
			<div class="container">
			  <div class="skills jurnal">80%</div>
			</div>
			<br>
	  </div>

	  <div class="col" style="background-color: #ffffff; margin: 1rem">
	  	<h1>Experiences</h1>
	  	<ul class="list-unstyled">
		  <li class="media">
		    <img class="mr-3 logowanita" src="http://icons.iconarchive.com/icons/dapino/teenage-girl/256/girl-swear-icon.png" alt="Generic placeholder image">
		    <div class="media-body">
		      <h5 style="font-size: 20px" class="mt-0 mb-1">Saya pernah menjadi</h5>
		      Staff of Press Compfest X
		    </div>
		  </li>
		  <li class="media my-4">
		    <img class="mr-3 logowanita" src="http://icons.iconarchive.com/icons/dapino/teenage-girl/256/girl-swear-icon.png" alt="Generic placeholder image">
		    <div class="media-body">
		      <h5 style="font-size: 20px" class="mt-0 mb-1">Saya pernah menjadi</h5>
		      Staff of BEM Media Fasilkom
		    </div>
		  </li>
		  <li class="media">
		    <img class="mr-3 logowanita" src="http://icons.iconarchive.com/icons/dapino/teenage-girl/256/girl-swear-icon.png" alt="Generic placeholder image">
		    <div class="media-body">
		      <h5 style="font-size: 20px" class="mt-0 mb-1">Saya pernah menjadi</h5>
		      PIC Mentor of Alfabeta
		    </div>
		  </li>
		  <li class="media">
		    <img class="mr-3 logowanita" src="http://icons.iconarchive.com/icons/dapino/teenage-girl/256/girl-swear-icon.png" alt="Generic placeholder image">
		    <div class="media-body">
		      <h5 style="font-size: 20px" class="mt-0 mb-1">Saya pernah menjadi</h5>
		      Staff of Creative OH
		    </div>
		  </li>
		  <li class="media">
		    <img class="mr-3 logowanita" src="http://icons.iconarchive.com/icons/dapino/teenage-girl/256/girl-swear-icon.png" alt="Generic placeholder image">
		    <div class="media-body">
		      <h5 style="font-size: 20px" class="mt-0 mb-1">Saya pernah menjadi</h5>
		      Staff PEMIRA FASILKOM 2017
		    </div>
		  </li>
		</ul>

	  </div>
	</div>
{% endblock %}

home_story4/templates/regis_story3.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
	<div class="bg1" style="height: 100%">
		<form>
			<div class="form-group">
			    <div class="col">
			    	<label for="exampleInputName">Your name</label>
			      <input type="text" class="form-control" placeholder="Your Name">
			    </div>
		    </div>
		    <div class="form-group">
			    <div class="col">
			    	<label for="InputDate">Your birth date</label>
			      <input type="date" class="form-control" id="inputdate">
			    </div>
		    </div>
		    <div class="form-group">
			    <label for="exampleInputEmail1">Email address</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
			    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			</div>
			<div class="form-group">
				<label for="exampleInputUsername">Username</label>
				<input type="Username" class="form-control" id="exampleInputUsername" placeholder="Username">
			</div>
			 <div class="form-group">
			    <label for="exampleInputPassword1">Password</label>
			    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
			 </div>
			 <div class="form-group">
			    <label for="exampleInputPassword1">Confirmation Password</label>
			    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
			 </div>
			  <div class="form-group form-check">
			    <input type="checkbox" class="form-check-input" id="exampleCheck1">
			    <label class="form-check-label" for="exampleCheck1">Check me out</label>
			  </div>
			  
			  <a href="{% url 'jasmine:welcomepage' %}">
			  <button type="button" class="btn btn-outline-success">Submit</button></a>
			  <br>
	</div>
{% endblock%}

home_story4/templates/table.html
    {% extends 'navbar.html' %}

    
    {% block content %}
    {% load static %}
    <h1>My Schedules</h1>
    <!--  Populate semua isi pesan dari model -->
    <table class="table">
        <thead>
            <th>Tempat</th>
            <th>Nama Kegiatan</th>
            <th>Kategori</th>
            <th>Tanggal</th>
            <th>Pukul</th>

        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in schedules %}
           
                <td> {{i.place}} </td>
                <td> {{i.event}} </td>
                <td> {{i.category}} </td>
                <td>{{i.date}}</td>
                <td>{{i.time}}</td>

            </tr>             
            {% endfor %}
        </tbody>
    </table>
    <br>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'jasmine:deleteJadwal' %}'">Delete Schedules</button>

    {% endblock %}

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> JasmineSafiera </title>
	<style>
	body {
		padding: 0 325px;
		font-family: 'Montserrat', sans-serif;
	}
	
	img {
		width: 200px;
		height: 200px;
		object-fit: cover;
	}
	
	.box {
		width: 600px;
		height: 900px;
		padding: 20px;
	}

	@media only screen and (max-width:600px){
	body {
		padding: 30px;
	}
	
	.box {
		width: 250px;
		height: 500px;
	}
	
	</style>
</head>
<body>
<style>
  body {
		background-image: url(https://xshyfc.com/wp-content/uploads/data/2018/2/17/Beautiful-Space-HD-Desktop-Wallpapersgorgerous-beautiful-space-hd-desktop-wallpapers-1920x1080-PIC-WPXH8964.jpg);
		background-size: cover;
		background-attachment:fixed;
		background-repeat:no-repeat
	}
  h1 {
	color: yellow;
	font-size: 24px;
  }
  p {color: yellow;}
</style>


<div class="box" style="background-color:Gray; opacity: 0.8;" >
<center>
<img src="http://www.about.tarung2017.com/foto/315.jpg" alt="cypher" >
    <h1>Hello my name is Jasmine Nur Safiera </h1>
    <article>NPM : 1706024841 </article>
    <article>I am 19 years old</article>
	
	<p> Just an ordinary girl who like to see galaxy with you *wink* </p>
	</div>
	
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}